FROM node:22-slim AS builder
WORKDIR /app
COPY ./client/package*.json .
RUN npm install
COPY ./client/ .
RUN sed -i 's#http://localhost:3001/api#/api#g' src/App.jsx
RUN npm run build

FROM nginx:alpine
ENV TZ=Asia/Jakarta
COPY --from=builder /app/dist /usr/share/nginx/html
COPY ./docker/nginx.conf /etc/nginx/nginx.conf
